config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'events#index'
  
  resources :events do
    resources :attendances
  end
  
  resources :users

  namespace :admin do
    resources :users
    root 'admin/users#index'
  end
  
end

app/models/event.rb
require 'date_validator'
class Event < ApplicationRecord

  validates :start_date, presence: true #date: { after: { Date.today } }
  validates :duration, presence: true #:modulo_five
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000}
  validates :location, presence: true  
  
  has_many :attendances
  has_many :guests, through: :attendances
  belongs_to :admin, class_name: "User"

  ###############################################################

  private

  def modulo_five
    errors.add("Doit être un multiple de 5.") unless :duration % 5 == 0 
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @participated = participated?
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :admin_id,  :price, :location)
    end

    def participated?
      Event.find(params[:id]).guests.ids
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_banner.html.erb
<!DOCTYPE html>
<body>
  <div class="container-fluid py-5">
    <p class="col-md-6 fs-3 ms-5">Bienvenue sur Eventbrite, créer des évènements de folies et rassemblez un max de monde.</p>
    <img class="justify-content-end"<%= image_tag("event.jpeg", :alt => "stars") %>>
    <h1 class="display-5 fw-bold">EVENTBRITE/thp</h1>
   
    <button class="btn btn-primary btn-lg justify-content-end" type="button">Créer Event</button>
  </div>
</body>

app/views/events/_cards.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="row align-middle shadow p-3 mb-5 mt-5 justify-content-center">
      <% @events.each do |event| %>
        <div class="card mt-5 ms-5 me-5" style="width: 18rem;">
          <%= image_tag("glare.jpg", :alt => "stars") %>
          <div class="card-body mt-3">
            <h4 class="card-title">Titre de l'évent <%= event.title %></h4>
            <h6 class="card-subtitle mb-2 ">Lieu: <%= event.location %></h6>
            <%= link_to 'Montrez moi!', event %>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> Evènement non validé pour les raisons suivantes:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container text-dark b fs-4 ">
 <div class="field">
    <%= form.label :admin_id%>
    <%= form.hidden_field :admin_id, value: current_user.id %>
  </div>
<br>
  <div class="field">
    <%= form.label :date_de_début %>
    <%= form.datetime_select :start_date %>
  </div>
<br>
  <div class="field">
    <%= form.label :Durée %>
    <%= form.number_field :duration %>
  </div>
<br>
  <div class="field">
    <%= form.label :Thème %>
    <%= form.text_field :title %>
  </div>
<br>
  <div class="field">
    <%= form.label :Description %>
    <%= form.text_area :description %>
  </div>
<br>
  <div class="field">
    <%= form.label :Prix %>
    <%= form.number_field :price %>
  </div>
<br>
  <div class="field">
    <%= form.label :Lieu %>
    <%= form.text_field :location %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/events/_show.html.erb
<body class="ms-5 me-5">
  <div class="card mb-3 mt-5 ms-5 me-5">
    <h3 class="card-header">Nom de l'event:</h3>
    <div class="card-body">
      <h5 class="card-title">Nom de l'administrateur:</h5>
      <h6 class="card-subtitle text-muted">Ville:</h6>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="200"
      aria-label="Placeholder: Image cap" focusable="false" role="img" preserveAspectRatio="xMidYMid slice"
      viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle">
      <rect width="100%" height="100%" fill="#868e96"></rect>
      <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image</text>
    </svg>
    <div class="card-body">
      <p class="card-text">Description de l'event: .</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Cras justo odio</li>
      <li class="list-group-item">Dapibus ac facilisis in</li>
      <li class="list-group-item">Vestibulum at eros</li>
    </ul>
    <div class="card-body">
      <a href="#" class="card-link">Voir page</a>
      <a href="index.html" class="card-link">Retour</a>
    </div>
    <div class="card-footer text-muted">
      2 days ago
    </div>
  </div>
  <div class="card mt-5 ms-5 me-5">
    <div class="card-body">
      <h4 class="card-title">Titre de l'évent</h4>
      <h6 class="card-subtitle mb-2 text-muted">CNom de l'admin:</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
        content.</p>
      <a href="#" class="card-link">Voir l'évent</a>
      <a href="#" class="card-link">Another link</a>
    </div>
  </div>
</body>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <%=render "banner"%>
    <%=render "cards"%>
  </body>
</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>
</html>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event.duration %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<% if user_signed_in? && current_user.id == @event.admin.id %>

  <p>    
    <strong class="text-success">TU ES L'ADMNISTRATEUR DE CET ÉVÈNEMENT</strong>
  </p>
  <%= link_to 'Voir la liste des participants', event_attendances_path(@event.id), :class=>"btn btn-warning btn-rounded" %>
  <% elsif user_signed_in? && current_user.id != @event.admin.id %>

  <p>
    <strong>Administrateur:</strong>
    <a href="<%= user_path(@event.admin.id)%>"><%= @event.admin.email %></a>
  </p>

  <% if @participated.include? current_user.id %>
    <button type="button" class="btn btn-success">Vous participez bien à l'évènement</button>
  <% else %>
  <p><%= link_to "S'inscrire à l'évènement", new_event_attendance_path(params[:id]), :class=>"btn btn-dark btn-rounded" %>
  </p>
  <% end %>

  <p>    
    <a href="<%= new_event_attendance_path(params[:id]) %>"><strong>PARTICIPER À L'ÉVÈNEMENT</strong></a>
  </p>

  <% else %>

  <p>
    <strong>Administrateur:</strong>
    <a href="<%= user_path(@event.admin.id)%>"><%= @event.admin.email %></a>
  </p>

  <p>    
    <a href="<%= new_user_session_path %>"><strong>SE CONNECTER POUR PARTICIPER À L'ÉVÈNEMENT</strong></a>
  </p>
  <% end %>

<%= link_to 'Edit', event_attendance_path(@event) %> |
<%= link_to 'Back', events_path %>