config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'events#index'
  
  resources :events do
    resources :attendances
  end
  
  resources :users

  namespace :admin do
    resources :users
    root 'admin/users#index'
  end
  
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  after_create :new_guest_email_send

  def new_guest_email_send
    AttendanceMailer.new_guest_email(self).deliver_now
  end

  validates :stripe_customer_id, uniqueness: true

  belongs_to :guest, class_name: "User"
  belongs_to :event, optional: true

end
 

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  before_action :set_attendance, only: %i[ show edit update destroy ]


  # GET /attendances or /attendances.json
  def index
    @attendances =  Attendance.where(event_id: params[:event_id])
  end

  # GET /attendances/1 or /attendances/1.json
  def show
    @attendance = Attendance.find(@attendance.id)
  end

  # GET /attendances/new
  def new
    @user = current_user
    @attendance = Attendance.new
    @event = Event.find(params[:event_id])
  end

  # GET /attendances/1/edit
  def edit
    @event = Event.find(params[:event_id])
  end

  # POST /attendances or /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)
    @user = current_user
    #_____ script stripe
      
    @event = Event.find(params[:event_id])
    @amount = @event.price
    @stripe_amount = (@amount * 100).to_i
      
    begin
      customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
      })
      charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @stripe_amount,
      description: "Achat d'un produit",
      currency: 'eur',
      })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_order_path
    end
    
    @stripe_customer_id = customer.id
      # --- reponse to
        respond_to do |format|
          if @attendance.save 
           format.html { redirect_to event_attendance_path(params[:event_id],@attendance.id), notice: "Attendance was successfully created." }
           format.json { render :show, status: :created, location: @attendance }
           a = Attendance.find(@attendance.id)
           a = a.update(stripe_customer_id: @stripe_customer_id)
         else
           format.html { render :new, status: :unprocessable_entity }
           format.json { render json: @attendance.errors, status: :unprocessable_entity }
         end
        end
        
      end
    
  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: "Attendance was successfully updated." }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: "Attendance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.permit(:event_id, :guest_id)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with url: event_attendances_path(params[:event_id]),local: true, method: :post do |form| %>

  

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, value: @event.id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :guest_id, value: current_user.id %>
  </div>

<%= form_tag event_attendances_path do %>
  <article>
  <%if @event.price !=0%>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Son prix est de : <%=@event.price %> €</span>
    </label>
  </article>
  <br/>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="Achat d'un produit"
  data-amount=<%= @stripe_amount %>
  data-currency="eur"
  data-locale="auto"></script>
  


<%else%>
  <div class="actions">
    <%= form.submit %>
  </div>
<%end%>
<%end%>
<%end%>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Stripe customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.stripe_customer_id %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_event_attendance_path %>

app/views/attendances/new.html.erb
<h1>Nouvelle participation</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', events_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stripe customer:</strong>
  <%= @attendance.stripe_customer_id %>
</p>

<%= link_to 'Edit', edit_event_attendance_path(@attendance) %> |
<%= link_to 'Back', event_attendance_path %>