config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'events#index'
  
  resources :events do
    resources :attendances
  end
  
  resources :users

  namespace :admin do
    resources :users
    root 'admin/users#index'
  end
  
end

app/views/layouts/_flash.html.erb
<!DOCTYPE html>
<html>
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

</html>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<footer class="mainfooter" role="contentinfo">
  <div class="footer-middle align-self-end">
    <div class="container ">
      <div class="row">
        <div class="col-md-3 col-sm-6">
          <!--Column1-->
          <div class="footer-pad">
            <h4>Heading 1</h4>
            <ul class="list-unstyled">
              <li><a href="#"></a></li>
              <li><a href="#">Payment Center</a></li>
              <li><a href="#">Contact Directory</a></li>
              <li><a href="#">Forms</a></li>
              <li><a href="#">News and Updates</a></li>
              <li><a href="#">FAQs</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <!--Column1-->
          <div class="footer-pad">
            <h4>Heading 2</h4>
            <ul class="list-unstyled">
              <li><a href="#">Website Tutorial</a></li>
              <li><a href="#">Accessibility</a></li>
              <li><a href="#">Disclaimer</a></li>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">FAQs</a></li>
              <li><a href="#">Webmaster</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <!--Column1-->
          <div class="footer-pad">
            <h4>Heading 3</h4>
            <ul class="list-unstyled">
              <li><a href="#">Parks and Recreation</a></li>
              <li><a href="#">Public Works</a></li>
              <li><a href="#">Police Department</a></li>
              <li><a href="#">Fire</a></li>
              <li><a href="#">Mayor and City Council</a></li>
              <li>
                <a href="#"></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <h4>Follow Us</h4>
          <ul class="social-network social-circle">
            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 copy">
          <p class="text-center">&copy; Copyright 2021 - EventBrite/thp. All rights reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<header>
  <nav class="ms-5 me-5 mt-5 mb-5 navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%=events_path%>">EventBrite/thp</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
        aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link text-light" href="<%= new_event_path %>">Créer Event</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true"
              aria-expanded="false">Identification</a>
            <div class="dropdown-menu">
            <%if user_signed_in? %>
              <a class="dropdown-item" <%= link_to "Profil",user_path(current_user.id)%></a>
              <a class="dropdown-item" <%= link_to "Deconnexion",destroy_user_session_path, method: :delete%></a>
            <%else%>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="<%= new_user_registration_path %>">S'incrire</a>
              <a class="dropdown-item" href="<%= new_user_session_path %>">Se Connecter</a>
            <%end%>
            </div>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-sm-2" type="text" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvenBrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <title> Navbar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
    crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>     
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>
  <%=render "layouts/navbar"%>
  <body>
  <%= render "layouts/flash"%>
  <%= yield %>  
  </body>
  <%= render "layouts/footer"%>
</html>